### PR TITLE
Pass ISC_REQ_USE_SUPPLIED_CREDS to InitializeSecurityContext

### LINKED ISSUE #23: Can't connect to cert-requesting servers without client cert
When using this crate to connect to a TLS server that requests a client certificate, and no client certificate was configured by the program, the connection fails with the error `SEC_I_INCOMPLETE_CREDENTIALS`.

```rust
extern crate schannel;

use std::net::TcpStream;
use std::io::{self, Write};

use schannel::schannel_cred::{SchannelCred, Direction};
use schannel::tls_stream::{Builder as TlsStreamBuilder};

fn main() {
	let s = TcpStream::connect(std::env::args().nth(1).unwrap()).unwrap();
    let mut s = TlsStreamBuilder::new().connect(SchannelCred::builder().acquire(Direction::Outbound).unwrap(), s).unwrap();
	s.write_all(b"GET / HTTP/1.0\r\n\r\n").unwrap();
	io::copy(&mut s, &mut io::stdout()).unwrap();
}
```

```
$ cargo run auth.mit.edu:444
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(Error { repr: Os { code: 590624, message: "The credentials supplied were not complete, and could not be verified. Additional information can be returned from the context." } })', C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libcore\result.rs:868
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I'm actively investigating solutions.

### PR DESCRIPTION
**Pull request by jethrogb**
Fixes #23. As mentioned in there, not sure if this is the behavior you want.

### CODE REVIEW

**Comment by sfackler** [comment]
From the documentation, it sounds like this flag may not solve the problem described in #23?

> When this flag is specified, Schannel will return SEC_I_INCOMPLETE_CREDENTIALS to the client when the server requests authentication and the client has not previously supplied a certificate.

https://msdn.microsoft.com/en-us/library/windows/desktop/aa378819(v=vs.85).aspx

**Comment by steffengy** [comment]
@jethrogb's testing and common usage such as 
https://github.com/curl/curl/blob/07fd7871b38cc8472c3806e254ba4062e3adeae0/lib/vtls/schannel.c#L594

seems to indicate that the documentation is off (once again).

**Comment by sfackler** [comment]
We would need a similar check for that error code, right: https://github.com/curl/curl/blob/07fd7871b38cc8472c3806e254ba4062e3adeae0/lib/vtls/schannel.c#L592

**Comment by steffengy** [comment]
In short, If we want the same behavior, yes.

#### Behavior 1 CURL
- First attempt to connect the server, leaving users certificates to schannel (which will look through several stores trying to find something that might work and sending it to the server)
- If the connection fails with `SEC_I_INCOMPLETE_CREDENTIALS`, pass `ISC_REQ_USE_SUPPLIED_CREDS` to prevent SCHANNEL from sending any certificates (since it/we do not pass any to it). 

==> Potentially unwanted that certificates are sent automatically?

#### Other behavior (as of this PR)
The more sensible alternative would be to rely on `ISC_REQ_USE_SUPPLIED_CRED` for all cases.
This would [apparently](https://groups.google.com/forum/#!msg/microsoft.public.platformsdk.security/lb-9guU8-D8/tgBBECWKyLYJ) only send the certificate associated with the acquired credential handle. 

We already pass certificates to `AcquireCredentialHandle` so this behavior should
also work out of the box (not sure if client auth is/was used before).

**Comment by sfackler** [comment]
Ah, right, misread that check. LGTM

**Pull request merged**
