### PR TITLE
Update windows-sys to 0.42

### PR DESCRIPTION
**Pull request by lazka**
https://github.com/microsoft/windows-rs/releases/tag/0.42.0

### CODE REVIEW

**Comment by messense** [comment]
Ping, the ecosystem is moving to windows-sys 0.42.0, `schannel` is the only one depends on 0.36 in my dependency tree right now. Please merge this and publish a new version, thanks a lot!

**Comment by messense** [comment]
I suppose this is blocked by the MSRV bump to 1.48.0, https://github.com/steffengy/schannel-rs/issues/75#issuecomment-1117096654 says

> The actual requirement for non-breaking with native-tls and other important dependents probably is something like 1.46.0. As long as that and no other major dependents break, edition / msrv should not matter much.

just FYI, `native-tls` now actually requires Rust 1.53.0: https://github.com/sfackler/rust-native-tls/issues/222

**Comment by marcograss** [comment]
is there any update on this? any blocker? can I help?

thanks

marco

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
