### PR TITLE
migrate to winapi 0.3

### PR DESCRIPTION
**Pull request by steffengy**
this is just an upgrade of internals and adds no new behavior (hopefully)

### CODE REVIEW

**Comment by sfackler** [comment]
I think we may now be able to get rid of the libncrypt archives as well.

**Comment by steffengy** [comment]
@sfackler 
Yep finally, took care of that aswell.
I also tried to find all FIXME/TODOS related to this, hopefully I got most of them.

Time improvement is clearly noticable: An appveyor test run took about 7 minutes before,
now we're down to about 5 minutes.

I used `use winapi::shared::minwindef as winapi;` to keep the diff somewhat better readable
and grew to actually not hating it that way, so let me know during your review if you
think it's better to get rid of that :)

**Comment by sfackler** [comment]
The module paths in winapi match up to include paths of the C header, right? The current diff seems reasonable to me.

**Comment by steffengy** [comment]
> The module paths in winapi match up to include paths of the C header, right? The current diff seems reasonable to me.

That was the plan as far as I know and also seemed to be the case where I checked.
I quite like how much faster it's locally, not sure if that's due to a new rust version 
but it feels at least twice as fast.

Do we have any exposed surface for winapi?
(if so, we'd have to consider this a breaking change and make sure to bump to 0.2 after merging this)

**Comment by sfackler** [comment]
I don't think we expose winapi anywhere so it shouldn't require an 0.2.

**Comment by steffengy** [comment]
yeah, and if there was an winapi type in some public API, I'd likely consider that the issue.
I also didn't spot anything while looking through the docs.

**Pull request merged**
